# Generated by Django 4.1.5 on 2023-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='sector',
            field=models.ManyToManyField(related_name='employers', to='sectors.sector'),
        ),
    ]
