# Generated by Django 4.1.5 on 2023-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('salaries', '0002_salary_salary_benchmark_salary_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='sector',
        ),
        migrations.AddField(
            model_name='salary',
            name='sector',
            field=models.ManyToManyField(related_name='salaries', to='sectors.sector'),
        ),
    ]
