# Generated by Django 4.1.5 on 2023-01-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Vacancy',
        ),
    ]
