# Generated by Django 4.1.5 on 2023-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('vacancies', '0002_rename_vacancies_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employer',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ManyToManyField(related_name='vacancies', to='employers.employer'),
        ),
    ]
